# Generated by Django 2.2.5 on 2019-09-14 23:10

from django.db import migrations, models
import reuse_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='loc_lat',
            field=reuse_app.models.CoordinateField(decimal_places=6, default=42.3598, max_digits=9),
        ),
        migrations.AddField(
            model_name='listing',
            name='loc_lng',
            field=reuse_app.models.CoordinateField(decimal_places=6, default=-71.0921, max_digits=9),
        ),
        migrations.AlterField(
            model_name='listing',
            name='loc_text',
            field=models.CharField(blank=True, max_length=32, verbose_name='Where?'),
        ),
    ]
