# Generated by Django 2.2.5 on 2019-09-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse_app', '0002_auto_20190914_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
