# Generated by Django 2.2.5 on 2019-09-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuse_app', '0003_listing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='marked_taken',
            field=models.BooleanField(default=False),
        ),
    ]
